// Pokemon Chinese localization data for Generation 1 (151 Pokemon)

const POKEMON_CN_NAMES = {
    1: '妙蛙种子',
    2: '妙蛙草',
    3: '妙蛙花',
    4: '小火龙',
    5: '火恐龙',
    6: '喷火龙',
    7: '杰尼龟',
    8: '卡咪龟',
    9: '水箭龟',
    10: '绿毛虫',
    11: '铁甲蛹',
    12: '巴大蝶',
    13: '独角虫',
    14: '铁壳蛹',
    15: '大针蜂',
    16: '波波',
    17: '比比鸟',
    18: '大比鸟',
    19: '小拉达',
    20: '拉达',
    21: '烈雀',
    22: '大嘴雀',
    23: '阿柏蛇',
    24: '阿柏怪',
    25: '皮卡丘',
    26: '雷丘',
    27: '穿山鼠',
    28: '穿山王',
    29: '尼多兰',
    30: '尼多娜',
    31: '尼多后',
    32: '尼多朗',
    33: '尼多力诺',
    34: '尼多王',
    35: '皮皮',
    36: '皮可西',
    37: '六尾',
    38: '九尾',
    39: '胖丁',
    40: '胖可丁',
    41: '超音蝠',
    42: '大嘴蝠',
    43: '走路草',
    44: '臭臭花',
    45: '霸王花',
    46: '派拉斯',
    47: '派拉斯特',
    48: '毛球',
    49: '摩鲁蛾',
    50: '地鼠',
    51: '三地鼠',
    52: '喵喵',
    53: '猫老大',
    54: '可达鸭',
    55: '哥达鸭',
    56: '猴怪',
    57: '火爆猴',
    58: '卡蒂狗',
    59: '风速狗',
    60: '蚊香蝌蚪',
    61: '蚊香君',
    62: '蚊香泳士',
    63: '凯西',
    64: '勇基拉',
    65: '胡地',
    66: '腕力',
    67: '豪力',
    68: '怪力',
    69: '喇叭芽',
    70: '口呆花',
    71: '大食花',
    72: '玛瑙水母',
    73: '毒刺水母',
    74: '小拳石',
    75: '隆隆石',
    76: '隆隆岩',
    77: '小火马',
    78: '烈焰马',
    79: '呆呆兽',
    80: '呆壳兽',
    81: '小磁怪',
    82: '三合一磁怪',
    83: '大葱鸭',
    84: '嘟嘟',
    85: '嘟嘟利',
    86: '小海狮',
    87: '白海狮',
    88: '臭泥',
    89: '臭臭泥',
    90: '大舌贝',
    91: '刺甲贝',
    92: '鬼斯',
    93: '鬼斯通',
    94: '耿鬼',
    95: '大岩蛇',
    96: '催眠貘',
    97: '引梦貘人',
    98: '大钳蟹',
    99: '巨钳蟹',
    100: '霹雳电球',
    101: '顽皮雷弹',
    102: '蛋蛋',
    103: '椰蛋树',
    104: '卡拉卡拉',
    105: '嘎啦嘎啦',
    106: '飞腿郎',
    107: '快拳郎',
    108: '大舌头',
    109: '瓦斯弹',
    110: '双弹瓦斯',
    111: '独角犀牛',
    112: '钻角犀兽',
    113: '吉利蛋',
    114: '蔓藤怪',
    115: '袋兽',
    116: '墨海马',
    117: '海刺龙',
    118: '角金鱼',
    119: '金鱼王',
    120: '海星星',
    121: '宝石海星',
    122: '魔墙人偶',
    123: '飞天螳螂',
    124: '迷唇姐',
    125: '电击兽',
    126: '鸭嘴火兽',
    127: '凯罗斯',
    128: '肯泰罗',
    129: '鲤鱼王',
    130: '暴鲤龙',
    131: '拉普拉斯',
    132: '百变怪',
    133: '伊布',
    134: '水伊布',
    135: '雷伊布',
    136: '火伊布',
    137: '多边兽',
    138: '菊石兽',
    139: '多刺菊石兽',
    140: '化石盔',
    141: '镰刀盔',
    142: '化石翼龙',
    143: '卡比兽',
    144: '急冻鸟',
    145: '闪电鸟',
    146: '火焰鸟',
    147: '迷你龙',
    148: '哈克龙',
    149: '快龙',
    150: '超梦',
    151: '梦幻',
    // Opponent team Pokemon (beyond Gen 1)
    257: '火焰鸡',
    282: '沙奈朵',
    376: '巨金怪',
    445: '烈咬陆鲨',
    658: '甲贺忍蛙'
};

const TYPE_CN_NAMES = {
    'normal': '一般',
    'fire': '火',
    'water': '水',
    'electric': '电',
    'grass': '草',
    'ice': '冰',
    'fighting': '格斗',
    'poison': '毒',
    'ground': '地面',
    'flying': '飞行',
    'psychic': '超能力',
    'bug': '虫',
    'rock': '岩石',
    'ghost': '幽灵',
    'dragon': '龙',
    'dark': '恶',
    'steel': '钢',
    'fairy': '妖精'
};

const MOVE_CN_NAMES = {
    'tackle': '撞击',
    'scratch': '抓',
    'ember': '火花',
    'flamethrower': '喷射火焰',
    'fire blast': '大字爆炎',
    'water gun': '水枪',
    'hydro pump': '水炮',
    'surf': '冲浪',
    'bubble': '泡沫',
    'vine whip': '藤鞭',
    'razor leaf': '飞叶快刀',
    'solar beam': '日光束',
    'thundershock': '电击',
    'thunderbolt': '十万伏特',
    'thunder': '打雷',
    'thunder wave': '电磁波',
    'quick attack': '电光一闪',
    'body slam': '泰山压顶',
    'take down': '猛撞',
    'double-edge': '舍身冲撞',
    'hyper beam': '破坏光线',
    'mega punch': '百万吨重拳',
    'mega kick': '百万吨重踢',
    'earthquake': '地震',
    'dig': '挖洞',
    'psychic': '精神强念',
    'confusion': '念力',
    'psybeam': '幻象光线',
    'ice beam': '冰冻光束',
    'blizzard': '暴风雪',
    'rock throw': '落石',
    'rock slide': '岩崩',
    'shadow ball': '暗影球',
    'lick': '舌舔',
    'night shade': '黑夜魔影',
    'dragon rage': '龙之怒',
    'dragon claw': '龙爪',
    'outrage': '逆鳞',
    'slash': '劈开',
    'fury swipes': '乱抓',
    'bite': '咬住',
    'crunch': '咬碎',
    'poison sting': '毒针',
    'sludge': '污泥攻击',
    'sludge bomb': '污泥炸弹',
    'toxic': '剧毒',
    'fly': '飞翔',
    'wing attack': '翅膀攻击',
    'peck': '啄',
    'drill peck': '啄钻',
    'string shot': '吐丝',
    'pin missile': '飞弹针',
    'leech life': '吸血',
    'absorb': '吸取',
    'mega drain': '超级吸取',
    'growth': '生长',
    'synthesis': '光合作用',
    'recover': '自我再生',
    'rest': '睡觉',
    'sleep powder': '催眠粉',
    'stun spore': '麻痹粉',
    'poison powder': '毒粉',
    'harden': '变硬',
    'withdraw': '缩入壳中',
    'defense curl': '变圆',
    'barrier': '屏障',
    'light screen': '光墙',
    'reflect': '反射壁',
    'agility': '高速移动',
    'double team': '影子分身',
    'minimize': '变小',
    'smokescreen': '烟幕',
    'confuse ray': '奇异之光',
    'supersonic': '超音波',
    'screech': '刺耳声',
    'leer': '瞪眼',
    'growl': '叫声',
    'roar': '吼叫',
    'sing': '唱歌',
    'metronome': '挥指',
    'self-destruct': '玉石俱碎',
    'explosion': '大爆炸',
    'skull bash': '火箭头锤',
    'submission': '地狱翻滚',
    'seismic toss': '地球上投',
    'counter': '双倍奉还',
    'low kick': '踢倒',
    'karate chop': '空手劈',
    'swift': '高速星星',
    'cut': '居合劈',
    'strength': '怪力',
    'stomp': '踩踏',
    'headbutt': '头锤',
    'horn attack': '角撞',
    'fury attack': '乱击',
    'pay day': '聚宝功',
    'mimic': '模仿',
    'transform': '变身',
    'substitute': '替身',
    // Opponent team moves
    'stone-edge': '尖石攻击',
    'fire-fang': '火之牙',
    'hydro-pump': '水炮',
    'dark-pulse': '恶之波动',
    'water-shuriken': '飞水手里剑',
    'flare-blitz': '闪焰冲锋',
    'high-jump-kick': '飞膝踢',
    'protect': '守住',
    'swords-dance': '剑舞',
    'meteor-mash': '彗星拳',
    'zen-headbutt': '意念头锤',
    'bullet-punch': '子弹拳',
    'waterfall': '攀瀑',
    'ice-fang': '冰之牙',
    'dragon-dance': '龙之舞',
    'moonblast': '月亮之力',
    'focus-blast': '真气弹'
};

// UI text translations
const UI_CN_TEXT = {
    'hp': '体力',
    'attack': '攻击',
    'defense': '防御',
    'special-attack': '特攻',
    'special-defense': '特防',
    'speed': '速度',
    'level': '等级',
    'exp': '经验值',
    'wild': '野生的',
    'appeared': '出现了',
    'fainted': '倒下了',
    'caught': '捕获',
    'escaped': '逃跑了',
    'victory': '胜利',
    'defeat': '失败'
};

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        POKEMON_CN_NAMES,
        TYPE_CN_NAMES,
        MOVE_CN_NAMES,
        UI_CN_TEXT
    };
}
